dist: trusty
language: node_js
sudo: false
node_js:
  - '8.6.0'

branches:
  only:
    - master
    - /^greenkeeper/.*$/

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - export CHROME_BIN=chromium-browser
  - npm run lint && npm run test:unit
  - codecov
